{% set name = "vastdb" %}
{% set version = "0.0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vastdb-{{ version }}.tar.gz
  sha256: ba13630e46bc879b048f6a9fc9b291c7fee732049a7120189ea1e475121a591a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-flatbuffers
    - pyarrow
    - requests
    - aws-requests-auth
    - xmltodict

test:
  imports:
    - vast_flatbuf
    - vastdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vast-data/vastdb_sdk
  summary: VAST Data SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
